import enum
import tkinter as tk
from PIL.ImageTk import PhotoImage
from dataclasses import dataclass
from typing import Any, Callable, Sequence

__version__: str

class EntryType(enum.Enum):
    STANDARD = 0
    CHECKBUTTON = 1
    RADIOBUTTON = 2

@dataclass
class ConfigInfo:
    entry_type: EntryType
    variable: tk.IntVar | None
    value: int
    def __init__(self, entry_type: EntryType = EntryType.STANDARD, variable: tk.IntVar | None = None, value: int = 0) -> None: ...

class Menu:
    parent: MainMenu | ContextMenu | Menu | None
    def __init__(self, text: str, image: PhotoImage | tk.PhotoImage | None = None) -> None: ...
    @property
    def count(self) -> int: ...
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, enabled: bool) -> None: ...
    @property
    def image(self) -> PhotoImage | tk.PhotoImage | None: ...
    @image.setter
    def image(self, image: PhotoImage | tk.PhotoImage | None) -> None: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, text: str) -> None: ...
    @property
    def visible(self) -> bool: ...
    @visible.setter
    def visible(self, visible: bool) -> None: ...
    def __iter__(self) -> Any: ...
    def __getitem__(self, index: int) -> MenuItem | Menu: ...
    def copy(self) -> Menu: ...
    def begin_update(self) -> None: ...
    def end_update(self) -> None: ...
    def add(self, entry: MenuItem | Menu) -> None: ...
    def add_item(self, text: str, command: Callable[..., None] | None = None, image: PhotoImage | tk.PhotoImage | None = None, config: ConfigInfo | None = None) -> MenuItem: ...
    def add_menu(self, text: str, image: PhotoImage | tk.PhotoImage | None = None) -> Menu: ...
    def add_range(self, entries: Sequence[MenuItem | Menu]): ...
    def add_separator(self) -> None: ...
    def clear(self) -> None: ...
    def insert(self, index: int, entry: MenuItem | Menu) -> None: ...
    def insert_item(self, index: int, text: str, command: Callable[..., None] | None = None, image: PhotoImage | tk.PhotoImage | None = None, config: ConfigInfo | None = None) -> MenuItem: ...
    def insert_menu(self, index: int, text: str, image: PhotoImage | tk.PhotoImage | None = None) -> Menu: ...
    def insert_separator(self, index: int) -> None: ...
    def index_of(self, entry: MenuItem | Menu) -> int: ...
    def remove(self, entry: MenuItem | Menu) -> None: ...
    def remove_at(self, index: int) -> None: ...

class MenuItem:
    parent: ContextMenu | Menu | None
    def __init__(self, text: str, command: Callable[..., Any] | None = None, image: PhotoImage | tk.PhotoImage | None = None, config: ConfigInfo | None = None) -> None: ...
    @property
    def checked(self) -> bool: ...
    @checked.setter
    def checked(self, status: bool) -> None: ...
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, enabled: bool) -> None: ...
    @property
    def image(self) -> PhotoImage | tk.PhotoImage | None: ...
    @image.setter
    def image(self, image: PhotoImage | tk.PhotoImage | None) -> None: ...
    @property
    def shortcut(self) -> str: ...
    @shortcut.setter
    def shortcut(self, key: str) -> None: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, text: str) -> None: ...
    @property
    def visible(self) -> bool: ...
    @visible.setter
    def visible(self, visible: bool) -> None: ...
    def copy(self) -> MenuItem: ...
    def set_custom_shortcut(self, sequence: str, accelerator: str) -> None: ...

class MainMenu:
    def __init__(self, parent: Any) -> None: ...
    @property
    def count(self) -> int: ...
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, enabled: bool) -> None: ...
    def begin_update(self) -> None: ...
    def end_update(self) -> None: ...
    def add(self, menu: Menu) -> None: ...
    def add_menu(self, text: str) -> Menu: ...
    def add_range(self, menus: list[Menu]) -> None: ...
    def insert(self, index: int, menu: Menu) -> None: ...
    def insert_menu(self, index: int, text: str) -> Menu: ...
    def index_of(self, menu: Menu) -> int: ...
    def remove(self, menu: Menu) -> None: ...
    def remove_at(self, index: int) -> None: ...

class ContextMenu(Menu):
    def __init__(self) -> None: ...
    def copy(self) -> ContextMenu: ...
    def display(self, location: tuple[int, int]) -> None: ...

class MenuButton(tk.Menubutton):
    def __init__(self, parent: Any, text: str = '', width: int = -1, image: PhotoImage | tk.PhotoImage | None = None) -> None: ...
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, enabled: bool) -> None: ...
    @property
    def image(self) -> PhotoImage | tk.PhotoImage | None: ...
    @image.setter
    def image(self, image: PhotoImage | tk.PhotoImage | None) -> None: ...
    @property
    def menu(self) -> Menu: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, text: str) -> None: ...

